
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: cr_weather_frontend
    ports:
      - "8090:80"
    depends_on:
      - backend
    networks:
      - weather_net
    restart: always

  backend:
    build: ./backend
    container_name: cr_weather_backend
    expose:
      - "8000"
    volumes:
      - weather_data:/app/data
    networks:
      - weather_net
    environment:
      - PYTHONUNBUFFERED=1
    restart: always

volumes:
  weather_data:

networks:
  weather_net:
    driver: bridge
